### ISSUE TITLE
GPS refs do not follow the exif standard

### ISSUE THREAD

**Issue by igorlopez** [TNThieding/exif#24]
I have just tried this tool to get the GPS location of images geo tagged by exiftool:
GPS Version ID                  : 2.3.0.0
GPS Latitude Ref                : South
GPS Longitude Ref               : East
GPS Altitude Ref                : Above Sea Level
GPS Time Stamp                  : 10:25:13
GPS Date Stamp                  : 2020:01:13
GPS Altitude                    : 403.9 m Above Sea Level
GPS Date/Time                   : 2020:01:13 10:25:13Z
GPS Latitude                    : 43 deg 11' 35.83" S
GPS Longitude                   : 171 deg 53' 40.26" E
GPS Position                    : 43 deg 11' 35.83" S, 171 deg 53' 40.26" E

Using exif in python gives me:
>>> data.gps_latitude
(43.0, 11.0, 35.833199679230155)
>>> data.gps_latitude_ref
'\x01'
>>> data.gps_longitude
(171.0, 53.0, 40.261200338123416)
>>> data.gps_longitude_ref
'\x00'

So from this I can "ASSUME" that in exif the value of 
gps_latitude_ref (type is string) means:
'\x00' -> 'N'
'\x01' -> 'S'
gps_longitude_ref (type is string) means:
'\x00' -> 'E'
'\x01' -> 'W'

But this should be documented or better yet changed such that the strings are 'N'/'S' and 'E'/'W' instead of '\x00'/'\x01'

**Comment by TNThieding** [comment]
I just released version 0.8.3 of the package (merge request [here](https://gitlab.com/TNThieding/exif/merge_requests/24)) which corrects this issue. The underlying problem was that strings of 3 characters or less (e.g., "N" or "S" in your case) are stored directly in the EXIF tag data structure rather than storing a pointer to another address in the file with the ASCII value (which is the typical behavior). The package now handles this case of having string of 3 characters or less, such as GPS refs. Don't hesitate to follow-up with an additional issue if necessary.
