### ISSUE TITLE
Support for other tags?

### ISSUE THREAD

**Issue by martimpassos** [TNThieding/exif#38]
Hi, I'm looking for a module that can write to "Artist", "UserComment", "Copyright" tags, among others. I'm finding it surprisingly difficult to find such a library, I've been using Pyexiftool but am looking for a pure python solution. Is the project still maintained and, if so, are there plans to include support to other tags in the near future? Thanks!

**Comment by TNThieding** [comment]
@martimpassos, this project is not maintained as much as I'd like to due to personal and work commitments. (Contributors always welcome!) However, I believe it already supports adding these 3 tags if I recall correctly. If this is not the case, please let me know, including posting stack traces if they'd be helpful. FYI, I generally commit to this project on GitLab (https://gitlab.com/TNThieding/exif), and this GitHub repository is a mirror for legacy purposes.

**Comment by martimpassos** [comment]
Ah yes, sorry for not digging deeper, I was thrown off by the README. The tags are already supported, thanks!
