### ISSUE TITLE
Feature request: return None for missing tags

### ISSUE THREAD

**Issue by gilesknap** [TNThieding/exif#7]
This library looks much nicer to use than any proceeding exif for python. Thanks!

I find myself using this pattern frequently
```
            try:
                # noinspection PyUnresolvedReferences
                uid = self.__exif.image_unique_id
            except AttributeError:
                uid = None
```

It would make nice concise code if there were an option to return None for non-existent tags.

**Comment by TNThieding** [comment]
Good idea! I plan on implementing this feature this week.

**Comment by TNThieding** [comment]
Upon further reflection, I don't think this change should be offered in the package. My intent is to the behavior of the ``Image`` class align as closely as possible to how Python objects behave natively. In standard objects, when a user accesses an attribute that does not exist, an ``AttributeError`` occurs. I think user scripts should be responsible for handling this case (e.g. as you are doing above) since different users may want different behavior when attributes are not present. I'm worried that returning ``None`` will give the user less error handling control and deviate from the "expected" behavior of objects.

Feel free to offer your perspective and any other explanations/justifications. I'm willing to change my mind if a good case is made for returning ``None``.

**Comment by gilesknap** [comment]
I think you make a good point.

Perhaps in the spirit of dictionaries, you could provide a 'get' function in addition to the standard behaviour?

I understand the ethos 'it is easier to ask for forgiveness than permission'. But in this case, I think it is expected that some tags may not be there on some files. As it stands, I can only use exception handling to discover which tags are present.

When I write code that is indexing dictionaries I would use get if I was expecting the index to be missing in some cases, and standard indexing with exception handling when the index should always be there.

**Comment by gilesknap** [comment]
I've been thinking a little more about this and although I like it, I wonder if using dynamic attributes to represent the tags is the best approach? 

For my application, it is fine since it is looking for a limited set of known tags.

But what if you wanted to write a tool that discovered all of the tags on a file and presented them all to the user, plus allowed her to edit/add arbitrary tags? Do you see a way of doing this using the attributes approach?

**Comment by TNThieding** [comment]
I like the idea of a ``get`` method that mimics dictionary behavior. I'll have a pull request up shortly for you to review. If a user wants to view a list of image tags, he can call pass the image to the ``dir`` builtin function and get a list of all attributes. Regarding your discussion of "arbitrary tags", could you please clarify what you mean? Right now, this package aligns with the tags outlined in the EXIF specification.

**Comment by TNThieding** [comment]
@gilesknap could you please let me know what you think of #9 at your earliest convenience? If satisfied with this change, I'll merge and deliver it.

**Comment by gilesknap** [comment]
I have looked at the #9 and it does resolve the original issue nicely.

Regarding the use of attributes. 

First I believe that some camera manufacturers add their own custom tags, do you know if they use arbitrary tag IDs when they do so?

But my main point is that using attributes makes it harder to iterate over the entire set of tags to do something like displaying them all to the user. This is because you would need an explicit line of code for every attribute instead of iterating over the set of keys.

However, the 'get' function now provides the ability to iterate. So I think this issue is fully resolved.

e.g. How would you have done the following, purely using attributes:-
```
import exif
with open('/media/Data/GilesPhotos/photos/2019/03/IMG_20190316_090920.jpg', 'rb') as image_file:
                ex = exif.Image(image_file)
for tag in dir(ex):
    try:
        print(tag, end=':  '),
        print(ex.get(tag))
    except (RuntimeError, ValueError) as e:
        print('!!! failed:', e)
```
UPDATE: the above fails for some attributes, I have made a comment in the PR

**Comment by TNThieding** [comment]
Thank you for pointing out those additional use cases. Could you please open (an) additional issue(s) regarding supporting custom attributes and handling the "unknown datatype value" case so we can keep the conversation going in a focused thread? (I'm closing out this issue since the original concern is addressed.)

Long term, I'd like to preserve attribute support where possible, but I also want to support custom attributes where used and offer other interfaces to tag data for other use cases and implementations.
